#!/usr/bin/env perl
# dump yuv file to a C array to fasten fread()
#
# scripts/generate-yuv.h.pl /the/path/of/1280x720.yuv > yuv.h
exit if $#ARGV < 0;
$_ = `od -vAn -tx1 $ARGV[0]`;
exit 1 if $? != 0;
chomp;
s/ /, 0x/g;
s/$/,/gm;
s/^, /\t/gm;
$template = <<"EOF";
/**
 * Do not edit this file!
 * generated by $0
 */
#include <stdint.h>
uint8_t yuv[] = {
$_
};
EOF
print $template;
