set(CMAKE_SYSTEM_NAME Generic)
if(NOT DEFINED TOOLCHAIN_SUFFIX)
  set(TOOLCHAIN_SUFFIX 6x)
endif()
set(CMAKE_C_COMPILER cl${TOOLCHAIN_SUFFIX})
set(CMAKE_CXX_COMPILER cl${TOOLCHAIN_SUFFIX})
string(TOUPPER ${TOOLCHAIN_SUFFIX} TOOLCHAIN_SUFFIX_UPPER)
if(NOT DEFINED ENV{C${TOOLCHAIN_SUFFIX_UPPER}_C_DIR})
  message(FATAL_ERROR "please define $C${TOOLCHAIN_SUFFIX_UPPER}_C_DIR")
endif()
file(GLOB ASM_SRC ${CMAKE_SOURCE_DIR}/common/*.sa)
add_compile_options(--gcc -mv64+)
add_link_options(-heap=0x1000000 -stack=0x1000000)
# avoid bug which cmake always convert `libc.a` to `c`
# https://discourse.cmake.org/t/how-to-stop-cmake-converting-libc-a-to-c/8121/1
find_program(CC_PATH REQUIRED NAMES ${CMAKE_C_COMPILER})
get_filename_component(BIN_PATH ${CC_PATH} DIRECTORY)
get_filename_component(ROOT_PATH ${BIN_PATH} DIRECTORY)
link_libraries(${ROOT_PATH}/lib/libc.a)
