---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            shell: bash
          - runs-on: macos-latest
            shell: bash
          - runs-on: windows-latest
            shell: msys2
    runs-on: ${{matrix.runs-on}}
    defaults:
      run:
        shell: ${{matrix.shell}} {0}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install meson
          ln -s meson.options meson_options.txt
      - name: Install dependencies
        if: runner.os == 'macOS'
        run: |
          brew install meson
      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
      - name: Install dependencies
        if: runner.os == 'Windows'
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-meson mingw-w64-x86_64-gcc
      - name: Build
        run: |
          meson setup build -Db_coverage=true -Dbuildtype=release
          meson compile -Cbuild
          meson test -Cbuild
          mv build/x264 build/${{matrix.runs-on}}-x264 ||
            mv build/x264.exe build/${{matrix.runs-on}}-x264.exe
      - uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            build/*-x264*

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: build
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
